[package]
name = "tls"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
helpers = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
