[package]
name = "labels"
version = "0.1.0"
edition = "2021"

[dependencies]
helpers = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
metrics-util = { workspace = true }
